[2020-11-20 23:45:13,933] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_confirmed 2020-11-17T00:00:00+00:00 [queued]>
[2020-11-20 23:45:14,018] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_confirmed 2020-11-17T00:00:00+00:00 [queued]>
[2020-11-20 23:45:14,026] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:45:14,028] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-11-20 23:45:14,033] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:45:14,122] {taskinstance.py:900} INFO - Executing <Task(BashOperator): fetch_covid_daily_confirmed> on 2020-11-17T00:00:00+00:00
[2020-11-20 23:45:14,129] {standard_task_runner.py:53} INFO - Started process 7275 to run task
[2020-11-20 23:45:14,549] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_confirmed 2020-11-17T00:00:00+00:00 [running]> 6600a3f3922a
[2020-11-20 23:45:14,644] {taskinstance.py:1145} ERROR - 'os' is undefined
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 964, in _run_raw_task
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1426, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 716, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 723, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 752, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'os' is undefined
[2020-11-20 23:45:14,649] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=us_covid_daily_report_pipeline, task_id=fetch_covid_daily_confirmed, execution_date=20201117T000000, start_date=20201120T234513, end_date=20201120T234514
[2020-11-20 23:45:23,733] {logging_mixin.py:112} INFO - [2020-11-20 23:45:23,733] {local_task_job.py:103} INFO - Task exited with return code 1
[2020-11-20 23:55:40,803] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_confirmed 2020-11-17T00:00:00+00:00 [queued]>
[2020-11-20 23:55:40,889] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_confirmed 2020-11-17T00:00:00+00:00 [queued]>
[2020-11-20 23:55:40,891] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:55:40,893] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-11-20 23:55:40,894] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:55:41,005] {taskinstance.py:900} INFO - Executing <Task(BashOperator): fetch_covid_daily_confirmed> on 2020-11-17T00:00:00+00:00
[2020-11-20 23:55:41,012] {standard_task_runner.py:53} INFO - Started process 454 to run task
[2020-11-20 23:55:41,523] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_confirmed 2020-11-17T00:00:00+00:00 [running]> 5fdb493b75fa
[2020-11-20 23:55:41,692] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-11-20 23:55:41,695] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmp_j4vp_ai/fetch_covid_daily_confirmedstmgmviv
[2020-11-20 23:55:41,705] {bash_operator.py:115} INFO - Running command: curl -o /opt/airflow/data/confirmed_20201117.json         --request GET 	    --url https://covid1910.p.rapidapi.com/data/confirmed/province/date/11-17-2020 	    --header 'x-rapidapi-host: covid1910.p.rapidapi.com' 	    --header 'x-rapidapi-key: None'
[2020-11-20 23:55:41,729] {bash_operator.py:122} INFO - Output:
[2020-11-20 23:55:41,747] {bash_operator.py:126} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2020-11-20 23:55:41,753] {bash_operator.py:126} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2020-11-20 23:55:41,858] {bash_operator.py:126} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100    31  100    31    0     0    281      0 --:--:-- --:--:-- --:--:--   284
[2020-11-20 23:55:41,861] {bash_operator.py:130} INFO - Command exited with return code 0
[2020-11-20 23:55:41,930] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=us_covid_daily_report_pipeline, task_id=fetch_covid_daily_confirmed, execution_date=20201117T000000, start_date=20201120T235540, end_date=20201120T235541
[2020-11-20 23:55:50,718] {logging_mixin.py:112} INFO - [2020-11-20 23:55:50,718] {local_task_job.py:103} INFO - Task exited with return code 0
