[2020-12-06 22:56:48,450] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.upload_file_to_s3 2020-12-03T00:00:00+00:00 [queued]>
[2020-12-06 22:56:48,509] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.upload_file_to_s3 2020-12-03T00:00:00+00:00 [queued]>
[2020-12-06 22:56:48,510] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-12-06 22:56:48,510] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2020-12-06 22:56:48,511] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-12-06 22:56:48,523] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): upload_file_to_s3> on 2020-12-03T00:00:00+00:00
[2020-12-06 22:56:48,530] {standard_task_runner.py:53} INFO - Started process 7837 to run task
[2020-12-06 22:56:48,645] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: us_covid_daily_report_pipeline.upload_file_to_s3 2020-12-03T00:00:00+00:00 [running]> 0d17e5047b06
[2020-12-06 22:56:48,970] {logging_mixin.py:112} INFO - [2020-12-06 22:56:48,970] {S3_hook.py:209} INFO - Not Found
[2020-12-06 22:56:49,165] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-12-06 22:56:49,186] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=us_covid_daily_report_pipeline, task_id=upload_file_to_s3, execution_date=20201203T000000, start_date=20201206T225648, end_date=20201206T225649
[2020-12-06 22:56:58,400] {logging_mixin.py:112} INFO - [2020-12-06 22:56:58,399] {local_task_job.py:103} INFO - Task exited with return code 0
