[2020-11-20 23:45:10,267] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_recovered 2020-11-16T00:00:00+00:00 [queued]>
[2020-11-20 23:45:10,449] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_recovered 2020-11-16T00:00:00+00:00 [queued]>
[2020-11-20 23:45:10,452] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:45:10,456] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-11-20 23:45:10,464] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:45:10,575] {taskinstance.py:900} INFO - Executing <Task(BashOperator): fetch_covid_daily_recovered> on 2020-11-16T00:00:00+00:00
[2020-11-20 23:45:10,583] {standard_task_runner.py:53} INFO - Started process 7171 to run task
[2020-11-20 23:45:11,341] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_recovered 2020-11-16T00:00:00+00:00 [running]> 6600a3f3922a
[2020-11-20 23:45:11,523] {taskinstance.py:1145} ERROR - 'os' is undefined
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 964, in _run_raw_task
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1426, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 716, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 723, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 752, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'os' is undefined
[2020-11-20 23:45:11,543] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=us_covid_daily_report_pipeline, task_id=fetch_covid_daily_recovered, execution_date=20201116T000000, start_date=20201120T234510, end_date=20201120T234511
[2020-11-20 23:45:19,963] {logging_mixin.py:112} INFO - [2020-11-20 23:45:19,963] {local_task_job.py:103} INFO - Task exited with return code 1
[2020-11-20 23:55:37,133] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_recovered 2020-11-16T00:00:00+00:00 [queued]>
[2020-11-20 23:55:37,248] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_recovered 2020-11-16T00:00:00+00:00 [queued]>
[2020-11-20 23:55:37,249] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:55:37,250] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-11-20 23:55:37,251] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:55:37,351] {taskinstance.py:900} INFO - Executing <Task(BashOperator): fetch_covid_daily_recovered> on 2020-11-16T00:00:00+00:00
[2020-11-20 23:55:37,362] {standard_task_runner.py:53} INFO - Started process 352 to run task
[2020-11-20 23:55:38,049] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_recovered 2020-11-16T00:00:00+00:00 [running]> 5fdb493b75fa
[2020-11-20 23:55:38,285] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-11-20 23:55:38,293] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmp0fcd0ezl/fetch_covid_daily_recoveredsojutyk8
[2020-11-20 23:55:38,299] {bash_operator.py:115} INFO - Running command: curl -o /opt/airflow/data/recovered_20201116.json         --request GET 	    --url https://covid1910.p.rapidapi.com/data/confirmed/province/date/11-16-2020 	    --header 'x-rapidapi-host: covid1910.p.rapidapi.com' 	    --header 'x-rapidapi-key: None'
[2020-11-20 23:55:38,337] {bash_operator.py:122} INFO - Output:
[2020-11-20 23:55:38,369] {bash_operator.py:126} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2020-11-20 23:55:38,375] {bash_operator.py:126} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2020-11-20 23:55:38,518] {bash_operator.py:126} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100    31  100    31    0     0    202      0 --:--:-- --:--:-- --:--:--   202
[2020-11-20 23:55:38,525] {bash_operator.py:130} INFO - Command exited with return code 0
[2020-11-20 23:55:38,678] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=us_covid_daily_report_pipeline, task_id=fetch_covid_daily_recovered, execution_date=20201116T000000, start_date=20201120T235537, end_date=20201120T235538
[2020-11-20 23:55:47,071] {logging_mixin.py:112} INFO - [2020-11-20 23:55:47,070] {local_task_job.py:103} INFO - Task exited with return code 0
