[2020-11-20 23:45:13,661] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_confirmed 2020-11-18T00:00:00+00:00 [queued]>
[2020-11-20 23:45:13,806] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_confirmed 2020-11-18T00:00:00+00:00 [queued]>
[2020-11-20 23:45:13,820] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:45:13,830] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-11-20 23:45:13,832] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:45:13,957] {taskinstance.py:900} INFO - Executing <Task(BashOperator): fetch_covid_daily_confirmed> on 2020-11-18T00:00:00+00:00
[2020-11-20 23:45:13,969] {standard_task_runner.py:53} INFO - Started process 7270 to run task
[2020-11-20 23:45:14,353] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_confirmed 2020-11-18T00:00:00+00:00 [running]> 6600a3f3922a
[2020-11-20 23:45:14,457] {taskinstance.py:1145} ERROR - 'os' is undefined
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 964, in _run_raw_task
    self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1426, in render_templates
    self.task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 716, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 723, in _do_render_template_fields
    rendered_content = self.render_template(content, context, jinja_env, seen_oids)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/baseoperator.py", line 752, in render_template
    return jinja_env.from_string(content).render(**context)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/home/airflow/.local/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'os' is undefined
[2020-11-20 23:45:14,470] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=us_covid_daily_report_pipeline, task_id=fetch_covid_daily_confirmed, execution_date=20201118T000000, start_date=20201120T234513, end_date=20201120T234514
[2020-11-20 23:45:23,498] {logging_mixin.py:112} INFO - [2020-11-20 23:45:23,497] {local_task_job.py:103} INFO - Task exited with return code 1
[2020-11-20 23:55:41,160] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_confirmed 2020-11-18T00:00:00+00:00 [queued]>
[2020-11-20 23:55:41,258] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_confirmed 2020-11-18T00:00:00+00:00 [queued]>
[2020-11-20 23:55:41,264] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:55:41,267] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2020-11-20 23:55:41,273] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-11-20 23:55:41,359] {taskinstance.py:900} INFO - Executing <Task(BashOperator): fetch_covid_daily_confirmed> on 2020-11-18T00:00:00+00:00
[2020-11-20 23:55:41,377] {standard_task_runner.py:53} INFO - Started process 465 to run task
[2020-11-20 23:55:41,903] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: us_covid_daily_report_pipeline.fetch_covid_daily_confirmed 2020-11-18T00:00:00+00:00 [running]> 5fdb493b75fa
[2020-11-20 23:55:42,091] {bash_operator.py:82} INFO - Tmp dir root location: 
 /tmp
[2020-11-20 23:55:42,095] {bash_operator.py:105} INFO - Temporary script location: /tmp/airflowtmptdj8t5f5/fetch_covid_daily_confirmedkoa3_dwm
[2020-11-20 23:55:42,096] {bash_operator.py:115} INFO - Running command: curl -o /opt/airflow/data/confirmed_20201118.json         --request GET 	    --url https://covid1910.p.rapidapi.com/data/confirmed/province/date/11-18-2020 	    --header 'x-rapidapi-host: covid1910.p.rapidapi.com' 	    --header 'x-rapidapi-key: None'
[2020-11-20 23:55:42,124] {bash_operator.py:122} INFO - Output:
[2020-11-20 23:55:42,159] {bash_operator.py:126} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2020-11-20 23:55:42,166] {bash_operator.py:126} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2020-11-20 23:55:42,301] {bash_operator.py:126} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100    31  100    31    0     0    216      0 --:--:-- --:--:-- --:--:--   216
[2020-11-20 23:55:42,307] {bash_operator.py:130} INFO - Command exited with return code 0
[2020-11-20 23:55:42,381] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=us_covid_daily_report_pipeline, task_id=fetch_covid_daily_confirmed, execution_date=20201118T000000, start_date=20201120T235541, end_date=20201120T235542
[2020-11-20 23:55:51,005] {logging_mixin.py:112} INFO - [2020-11-20 23:55:51,005] {local_task_job.py:103} INFO - Task exited with return code 0
