[2020-12-06 22:11:19,501] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.upload_file_to_s3 2020-12-02T00:00:00+00:00 [queued]>
[2020-12-06 22:11:19,549] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: us_covid_daily_report_pipeline.upload_file_to_s3 2020-12-02T00:00:00+00:00 [queued]>
[2020-12-06 22:11:19,549] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-12-06 22:11:19,550] {taskinstance.py:880} INFO - Starting attempt 3 of 3
[2020-12-06 22:11:19,550] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-12-06 22:11:19,560] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): upload_file_to_s3> on 2020-12-02T00:00:00+00:00
[2020-12-06 22:11:19,564] {standard_task_runner.py:53} INFO - Started process 19114 to run task
[2020-12-06 22:11:19,681] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: us_covid_daily_report_pipeline.upload_file_to_s3 2020-12-02T00:00:00+00:00 [running]> b87086861777
[2020-12-06 22:11:19,734] {taskinstance.py:1145} ERROR - module 'airflow.hooks.S3_hook' has no attribute 'S3hook'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/us_covid_daily_report_pipeline.py", line 11, in upload_file_to_S3_with_hook
    hook = S3_hook.S3hook('s3_connection')
AttributeError: module 'airflow.hooks.S3_hook' has no attribute 'S3hook'
[2020-12-06 22:11:19,738] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=us_covid_daily_report_pipeline, task_id=upload_file_to_s3, execution_date=20201202T000000, start_date=20201206T221119, end_date=20201206T221119
[2020-12-06 22:11:29,463] {logging_mixin.py:112} INFO - [2020-12-06 22:11:29,462] {local_task_job.py:103} INFO - Task exited with return code 1
